// Generated by gen_wifi_keyrom.py
// Packed Wi-Fi password (64-bit) - big-endian (first character -> MSB)
// Source file: D:\vivado_projects\WiFi_key_encrypt\WiFi_key_encrypt.srcs\sources_1\new\WiFi_Profile_Info.txt
// Extracted password (raw): 123harsh
module wifi_key_rom (
    output wire [63:0] m_out
);

    // 64-bit packed constant
    localparam [63:0] M_CONST = 64'h3132336861727368;
    assign m_out = M_CONST;

endmodule
